print("In a cavern, in a canyon")
print("Excavating for a mine")
print("Dwelt a miner forty niner,")
print("And his daughter Clementine")
print()
print("Chorus:")
print()
print("Oh my darling, oh my darling,")
print("Oh my darling, Clementine!")
print("Thou art lost and gone forever")
print("Dreadful sorry, Clementine")
print()
print("Light she was and like a fairy,")
print("And her shoes were number nine,")
print("Herring boxes without topses,")
print("Sandals were for Clementine. -- Chorus.")
print()
print("Drove she ducklings to the weter")
print("Ev'ry morning just at nine,")
print("Hit her foot against a splinter,")
print("Fell into the foaming brine. -- Chorus.")
    
